import React from 'react';
import './TermsConditions.module.css'

export default function TermsConditions() {
  return (<>
  <h2><strong> Guardian Capital Investment Advisors Website Terms of Service</strong></h2>
  <p>Welcome to our website.If you continue to browse and use this website,you are agreeing to comply with and be bound by the following terns and conditions of use,which together with our 'Privacy Policy',govern Guardian Capital Investment Advisors relationship with you.The term "Guardian Capital Advisors" (or"us"/"We"/"our") refers to the owner of the website.The term "you" refers to the user or viewer of our website.</p>
  <h3><strong>The use of this website is subject to the following terms:</strong></h3>
  <p>You understand and accept that Guardian Capital Investment Advisors maintains the website – https://www.gcia.in  or related websites (referred to as “site” or “website” on this page) to provide visitors with information about us, our services and products, and to enable visitors to avail our services. You also accept that visitors to the site are required to read the below terms, and the use of the site constitutes your acceptance and agreement to be bound by such terms. You will also be bound by changes therein to the terms from time to time as communicated and made available on the website.</p>
  <p>You are aware and accept that all information, content, materials, products (including, but not limited to text, content, photographs, graphics, video, and audio content) on the website is protected by copyright in favor of Guardian Capital Investment Advisors under the applicable copyright laws and the general intellectual property law.</p>
  <p>You understand and accept that all information submitted by you on the site shall be deemed the property of Guardian Capital Investment Advisors , and Guardian Capital Investment Advisors  shall be free to use any ideas, concepts, know-how, or techniques provided by you in any manner whatsoever. On initiating contact through the site, you agree to be contacted by Guardian Capital Investment Advisors, or any othre entities with whom <strong>Guardian Capital Investment Advisors</strong>  has entered into an arrangement, via email, phone call, SMS, or any other means. You agree that you shall not copy, reproduce, sell, redistribute, publish, enter into a database, display, perform, modify, transmit, license, create derivatives from, transfer, or in any way exploit, any part of any information, content, materials, services available on or through the site, except that which you may download for your own personal, non-commercial use.</p>
  <p>You agree that you will not use Guardian Capital Investment Advisors ’s website for any purpose that is unlawful or prohibited by these terms. You also agree you will not use the site in any manner that could damage, disable or impair the website, or interfere with any other party’s use, or enjoyment of the website.</p>
  <p>You acknowledge that the software and hardware underlying the site, as well as other Internet-related software required for accessing the website, are the legal property of the respective vendors. The permission given by Guardian Capital Investment Advisors  to access the website will not convey any proprietary or ownership rights in the above software/hardware. You agree that you shall not attempt to modify, translate, disassemble, decompile, or reverse engineer the software/ hardware underlying the website, or create any derivative product based on the software/hardware.</p>
  <p>You understand and accept that not all products and services offered on this website are available in all geographic areas, and you may not be eligible for all the products or services offered by Guardian Capital Investment Advisors  on the site. <strong>Guardian Capital Investment Advisors</strong>  reserves the right to determine the availability and eligibility for any product or service.</p>
  <p>You understand and accept that Guardian Capital Investment Advisors  is not responsible for the availability of content, or other services on third-party sites linked from the website. You are aware that the access of hyperlinks to other internet sites is at your own risk, and the content, accuracy, opinions expressed, and other links provided by these sites are not verified, monitored, or endorsed by Guardian Capital Investment Advisors  in any way. Guardian Capital Investment Advisors  does not make any warranties, and expressly disclaims all warranties, express or implied, including without limitation, those of merchantability and fitness for a particular purpose, title, or non-infringement with respect to any information or services or products that are available or advertised or sold through these third-party websites.</p>
  <p>Guardian Capital Investment Advisors shall not be liable if any transaction does not fructify, or may not be completed, or for any failure on the part of Guardian Capital Investment Advisors  to perform any of its obligations under these terms and conditions, or those applicable specifically to its services/facilities if performance is prevented, hindered or delayed by a Force Majeure event (defined below). In such a case, its obligations shall be suspended for so long as the Force Majeure event continues.</p>
  <p>“Force Majeure Event” means any event due to any cause beyond the reasonable control of Guardian Capital Investment Advisors , including and without limitations the unavailability of any communication systems, breach, or virus in the processes or payment or delivery mechanism, sabotage, fire, flood, explosion, acts of God, civil commotions, strikes or industrial action of any kind, riots, insurrection, war, acts of the government, computer hacking, unauthorized access to computer data and storage devices, computer crashes, malfunctioning in the computer terminal, or the systems getting affected by any malicious, destructive or corrupting code or programme, mechanical or technical errors/failures or power shutdown, faults or failures in telecommunication, etc.</p>
  <p>You understand and accept that Guardian Capital Investment Advisors  has the absolute discretion to amend or supplement any of the terms at any time, and will give prior notice of 30 days for such changes. The changed terms and conditions shall be communicated to you on the website, and by other acceptable modes of communication. By using Guardian Capital Investment Advisors’  services, you shall be deemed to have accepted the changed terms and conditions.</p>
  <p>You accept that the Courts in Chennai alone shall have exclusive jurisdiction as regards any claims or matters arising out of dealings with Guardian Capital Investment Advisors . All disputes will be governed by the laws of India. </p>
  <p>You understand and agree that these terms are in addition to, and not in derogation of, the applicable terms and conditions relating to your usage of any <strong>Guardian Capital Investment Advisors </strong>services that you may be currently availing, or may avail in the future.</p>
  </>
  )
}
